version: '3'

services:

  db:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    # ONLY for better testing experience - ensure migrations
    entrypoint: ./web-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

volumes:
    pgdata:
