# Generated by Django 2.0.8 on 2019-04-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
