# Generated by Django 2.0.8 on 2019-04-12 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='x',
            field=models.PositiveIntegerField(verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='y',
            field=models.PositiveIntegerField(verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[0, 0], null=True, size=None),
        ),
    ]
